# Form implementation generated from reading ui file 'C:\Users\yonat\PyCharmMiscProject\opening_screen.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OpeningScreen(object):
    def setupUi(self, OpeningScreen):
        OpeningScreen.setObjectName("OpeningScreen")
        OpeningScreen.resize(950, 700)
        OpeningScreen.setMaximumSize(QtCore.QSize(1200, 880))
        OpeningScreen.setStyleSheet("background-color: #fff9d6;")
        OpeningScreen.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(parent=OpeningScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(60, 80, 831, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setText("")
        self.titleLabel.setPixmap(QtGui.QPixmap("C:\\Users\\yonat\\PyCharmMiscProject\\Picture1.png"))
        self.titleLabel.setScaledContents(True)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(360, 300, 250, 55))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("QPushButton {\n"
"    background-color: #10B981;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 28px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #059669;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #047857;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.userGuideButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.userGuideButton.setGeometry(QtCore.QRect(360, 370, 250, 55))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.userGuideButton.setFont(font)
        self.userGuideButton.setStyleSheet("QPushButton {\n"
"    background-color: #3B82F6;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 28px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2563EB;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1D4ED8;\n"
"}")
        self.userGuideButton.setObjectName("userGuideButton")
        self.aboutButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.aboutButton.setGeometry(QtCore.QRect(360, 440, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.aboutButton.setFont(font)
        self.aboutButton.setStyleSheet("QPushButton {\n"
"    background-color: #00ebeb;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 28px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00cccc;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #009999;\n"
"}")
        self.aboutButton.setObjectName("aboutButton")
        self.titleLabel_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel_2.setGeometry(QtCore.QRect(120, 160, 721, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel_2.setFont(font)
        self.titleLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel_2.setObjectName("titleLabel_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 520, 150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\yonat\\PyCharmMiscProject\\neural-network.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        OpeningScreen.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=OpeningScreen)
        self.statusbar.setObjectName("statusbar")
        OpeningScreen.setStatusBar(self.statusbar)

        self.retranslateUi(OpeningScreen)
        QtCore.QMetaObject.connectSlotsByName(OpeningScreen)

    def retranslateUi(self, OpeningScreen):
        _translate = QtCore.QCoreApplication.translate
        OpeningScreen.setWindowTitle(_translate("OpeningScreen", "Welcome"))
        self.startButton.setText(_translate("OpeningScreen", "🚀 Start"))
        self.userGuideButton.setText(_translate("OpeningScreen", "📖 User Guide"))
        self.aboutButton.setText(_translate("OpeningScreen", "ℹ️ About"))
        self.titleLabel_2.setText(_translate("OpeningScreen", "Analyze Brain Connectivity Using Graph Theory"))
